backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
site_url: "https://CraftersAgainstCOVID19.org"
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/njk.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Post Feed Heading", name: "postsHeading", widget: "string", default: "Latest posts"}
          - {label: "Archive Link Text", name: "archiveButtonText", widget: "string", default: "See all posts"}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "faqs"
        label: "FAQs"
        file: "src/faq.md"
        slug: "{{slug}}"
        create: true
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/faq.njk"}
          - {label: "Title", name: "title", widget: "string", required: true, default: "Frequently Asked Questions"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/faq/index.html"}
          - {label: "Intro", name: "body", widget: "markdown", required: true}
          - label: "Sections"
            name: "sections"
            required: true
            widget: "list"
            fields:
              - {label: "Title", name: "name", widget: "string", required: true}
              - label: "Questions"
                name: "faq"
                required: true
                widget: "list"
                fields:
                  - {label: "Question", name: "q", widget: "string", required: true}
                  - {label: "Answer", name: "a", widget: "markdown", required: true}
      - label: "Mask Request Form"
        name: "request_form"
        delete: false
        file: "src/_data/request_form.json"
        fields:
          - {label: "Intro Text", name: "intro", widget: "markdown"}
          - {label: "Masks Text", name: "masks", widget: "markdown"}
          - {label: "Delivery Text", name: "delivery", widget: "markdown"}
  - name: "generic_pages"
    label: "Generic Pages"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Permalink Override (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "posts"
    label: "Announcements"
    folder: "src/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Excerpt", name: "excerpt", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "patterns"
    label: "Patterns"
    folder: "src/patterns"
    slug: "{{slug}}"
    preview_path: "patterns/{{slug}}"
    create: true
    fields:
      - {label: "Pattern Name", name: "title", widget: "string", required: true}
      - {label: "Brief Description", name: "description", widget: "string", required: false}
      - {label: "YouTube Video Slug (e.g., -GoWoPA3tF0)", name: "video", widget: "string", required: true}
      - {label: "PDF Instructions", name: "pdf", widget: "file", required: true}
      - {label: "Skill Level", name: "skill_level", widget: "select", options: ["Beginner", "Intermediate"], required: true }
      - {label: "Instructions", name: "body", widget: "markdown", required: true}
      - label: "Frequently Asked Questions"
        name: "faq"
        required: false
        widget: "list"
        fields:
          - {label: "Question", name: "question", widget: "string", required: true}
          - {label: "Answer", name: "answer", widget: "markdown", required: true}
  - label: "Globals"
    name: "globals"
    files:
      - label: "Mask Production Batches"
        name: "batches"
        file: "src/_data/batches.json"
        fields:
          - label: "Patterns"
            name: "patterns"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string", default: "Pick a number", required: true}
              - {label: "Name", name: "name", widget: "string", default: "Batch X", required: true}
              - {label: "Pattern URL (leave off the domain)", name: "url", widget: "string", default: "/patterns/fitted-mask/", required: true}
              - {label: "Skill Level", name: "level", widget: "select", options: ["Beginner", "Intermediate"], required: true }
          - label: "Batches"
            name: "list"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string", default: "Batch X", required: true}
              - {label: "Sign-up Start", name: "start", widget: "date", required: true, format: "YYYY-MM-DD"}
              - {label: "Sign-up Cutoff", name: "cutoff", widget: "date", required: true, format: "YYYY-MM-DD"}
              - {label: "Materials Available", name: "pickup", widget: "date", required: true, format: "YYYY-MM-DD"}
              - {label: "Complete By", name: "end", widget: "date", required: true, format: "YYYY-MM-DD"}
              - label: "Masks"
                name: "masks"
                widget: "list"
                fields: 
                  - {label: "Pattern ID (see above)", name: "pattern", widget: "string", required: true}
                  - {label: "Beneficiary Name", name: "beneficiary", widget: "string", required: true}
                  - {label: "Beneficiary URL", name: "beneficiary_url", widget: "string", required: false}
      - label: "Neighborhoods"
        name: "neighborhoods"
        file: "src/_data/neighborhoods.json"
        fields:
          - label: "Neighborhoods"
            name: "list"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Number of Masks Made", name: "masks_made", widget: "string", required: true}
          - {label: "Volunteer Activities", name: "volunteer_activities", required: true, widget: "list"}
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Author Email Address", name: "authorEmail", widget: "string"}
          - {label: "Author Twitter Handle", name: "authorHandle", widget: "string", required: false}
          - {label: "Footer Short Description", name: "shortDesc", widget: "string"}
          - {label: "Maximum Posts Per Page", name: "maxPostsPerPage", widget: "number", default: 5}
          - {label: "Show Theme Credit", name: "showThemeCredit", widget: "boolean", default: true}
          - {label: "Enable Third Party Comments Area", name: "enableThirdPartyComments", widget: "boolean", default: false}
          - {label: "Enable Forms", name: "forms", widget: "boolean", default: true}
          - {label: "Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)", name: "paymentPointer", widget: "string", required: false}
          - {label: "Favicon path (EG: /images/favicon.png)", name: "faviconPath", widget: "string"}
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Main Navigation"
            name: "main"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
          - label: "Footer Navigation"
            name: "footer"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
      - label: "Theme"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        fields:
          - label: "Size Scale"
            name: "size-scale"
            widget: "object"
            fields: 
              - {label: "Base Size", name: "base", widget: "string", default: "1rem"}
              - {label: "Ratio: 300", name: "300", widget: "string", default: "0.8rem"}
              - {label: "Ratio: 500", name: "500", widget: "string", default: "1.25rem"}
              - {label: "Ratio: 600", name: "600", widget: "string", default: "1.56rem"}
              - {label: "Ratio: 700", name: "700", widget: "string", default: "1.95rem"}
              - {label: "Ratio: 800", name: "800", widget: "string", default: "2.44rem"}
              - {label: "Ratio: 900", name: "900", widget: "string", default: "3.05rem"}
              - {label: "Max Size", name: "max", widget: "string", default: "4rem"}
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields: 
              - {label: "Primary", name: "primary", widget: "string", default: "hsl(208, 57%, 21%)"}
              - {label: "Primary Shade (darker)", name: "primary-shade", widget: "string", default: "hsl(208, 56%, 14%)"}
              - {label: "Primary Glare (lighter)", name: "primary-glare", widget: "string", default: "hsl(207, 57%, 31%)"}
              - {label: "Highlight", name: "highlight", widget: "string", default: "hsl(42, 98%, 77%)"}
              - {label: "Light", name: "light", widget: "string", default: "hsl(0, 0%, 100%)"}
              - {label: "Mid", name: "mid", widget: "string", default: "hsl(0, 0%, 80%)"}
              - {label: "Dark", name: "dark", widget: "string", default: "hsl(0, 0%, 20%)"}
              - {label: "Slate", name: "slate", widget: "string", default: "hsl(0, 0%, 25%)"}
          - label: "Fonts"
            name: "fonts"
            widget: "hidden"
            default: { "base": "\"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'\"", "serif": "\"'Lora', serif\""}
