name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This has gotten stale. Take a look or close it out.'
        stale-pr-message: 'This has gotten stale. Take a look or close it out.'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
